var config = {
    "general": {
        "SERVICE_BASE_URL": "https://tjose.internal.rmplc.net:504/",
        "ALLOW_CORS": true,
        "DISPLAY_SCRIPT_INFO": false,
        "AUDIT_LOG_LIMIT": 20,
        "STORAGE_ADAPTER_CACHE_TIME_IN_MINUTES": 60,
        "RETRY_ATTEMPT_COUNT": 3,
        "DATA_SERVICE_CALL_TIME_OUT": 84000,
        "NOTIFICATION_TIMER_INTERVAL": 600000,
        "SCRIPT_METADATA_LOAD_TIMER_INTERVAL": 1800000,
        "ECOURSEFILE_METADATA_LOAD_TIMER_INTERVAL": 30000,
        "IDLE_TIMEOUT": 1200000,
        "APPLICATION_ONLINE_CHECK_INTERVAL": 30000,
        "APPLICATION_OFFLINE_CHECK_INTERVAL": 5000,
        "PASSWORD_RESET_URL": "$$PASSWORD_CHANGE_WEBSITE_URL$$",
        "FORGOT_PASSWORD_URL": "$$FORGOT_PASSWORD_URL$$",
        "WEBPACK_HASH": "$$WEBPACK_HASH$$",
        "AI_URL": "$$AI_SERVICE_BASE_URL$$",
        "RESET_BUSY_INDICATOR_TIMEOUT": 60000,
        "ECOURSEFILE_METADATA_DOWNLOAD_BATCH_SIZE": 3,
        "ASSESSOR_AUTH_COOKIE_NAME": "$$AssessorAuthCookie$$",
        "CLOUD_IMAGE_RETRY_COUNT": 3
    },
    "backgroundworkerrefreshconfig": {
        "SCRIPT_IMAGE_DOWNLOADER": 3000,
        "BACKGROUND_IMAGES_DOWNLOAD_ENABLED": true
    },
    "cacheconfig": {
        "TWO_MINUTES_CACHE_TIME": 2,
        "THIRTY_MINUTES_CACHE_TIME": 30
    },
    "googleanalyticsconfig": {
        "GOOGLE_ANALYTICS_ENABLED": true,
        "GOOGLE_ANALYTICS_TRACKING_ID": "$$ANALYTICS_TRACK_CODE$$"
    },
    "marksandannotationsconfig": {
        "MARKS_AND_ANNOTATIONS_LOAD_TIMER_INTERVAL": 3000,
        "MARKS_AND_ANNOTATIONS_SAVE_TIMER_INTERVAL": 3000,
        "MARKS_AND_ANNOTATIONS_SAVE_RETRY_ATTEMPT_COUNT": 3,
        "AUTO_POPULATE_STAMPS_TO_FAVOUIRITES_COUNT": "$$AUTO_POPULATE_STAMPS_TO_FAVOUIRITES_COUNT$$",
        "AUTOSAVE_MARKS_AND_ANNOTATIONS_IN_RESPONSE_INTERVAL": 300000,
        "IGNORE_DIRTY_FLAG_AND_SAVE_ALL_MARKS_AND_ANNOTATIONS": false
    },
    "logger": {
        "LOGGING_ENABLED": true,
        "LOGGER_TYPE": "$$LOGGER_TYPE$$",
        "MAXIMUM_LOGS_FOR_BATCHSAVE": 1
    },
    "applicationinsightconfig": {
        "INSTRUMENTATION_KEY": "$$INSTRUMENTATION_KEY$$",
        "APPLICATION_VERSION": "$$APPLICATION_VERSION$$",
        "ROLE_NAME": "Assessor 3 Web"
    }
}