let keyMirror = require('keymirror');

// Constants for Grid Column Names.
// We need to add a new key for each column(same as in gridcolums.json) and use that for checking column names.
let gridColumnNames = keyMirror({
    MarkingProgress: 'MarkingProgress',
    TotalMark: 'TotalMark',
    ResponseIdColumn: 'ResponseIdColumn',
    LastUpdatedColumn: 'LastUpdatedColumn',
    AllocatedDate: 'AllocatedDate',
    LinkedMessageIndicator: 'LinkedMessageIndicator',
    LinkedExceptionIndicator: 'LinkedExceptionIndicator',
    GracePeriodTime: 'GracePeriodTime',
    AllPageAnnotedIndicator: 'AllPageAnnotedIndicator',
    AccuracyIndicator: 'AccuracyIndicator',
    MarksDifference: 'MarksDifference',
    SLAOIndicator: 'SLAOIndicator',
    AbsoluteMarksDifference: 'AbsoluteMarksDifference',
    TotalMarksDifference: 'TotalMarksDifference',
    OriginalMarkerInitials: 'OriginalMarkerInitials',
    OriginalMarkerName: 'OriginalMarkerName',
    CentreNum: 'CentreNum',
    CentreCandidateNum: 'CentreCandidateNum',
    ResponseTypeLabel: 'ResponseTypeLabel',
    MarkChangeReason: 'MarkChangeReason',
    Examiner: 'Examiner',
    TargetProgress: 'TargetProgress',
    State: 'State',
    LockedDuration: 'LockedDuration',
    LockedBy: 'LockedBy',
    ExceptionId: 'ExceptionId',
    ExceptionType: 'ExceptionType',
    TimeOpen: 'TimeOpen',
    SampleLabel: 'SampleLabel',
    ReviewedByLabel: 'ReviewedByLabel',
    ResponsesToReview: 'ResponsesToReview',
    Role: 'Role',
    Supervisor: 'Supervisor',
    TimeInCurrentState: 'TimeInCurrentState',
    SEPAction: 'SEPAction',
    SupervisorRemarkDecision: 'SupervisorRemarkDecision',
    OriginalMark: 'OriginalMark',
    OriginalMarkAccuracy: 'OriginalMarkAccuracy',
    Finalmarkselected: 'Finalmarkselected',
    TagIndicator: 'TagIndicator',
    Item: 'Item',
    File: 'File',
    Comment: 'Comment',
    AllFilesNotViewedIndicator: 'AllFilesNotViewedIndicator',
    SupervisorReviewComment: 'SupervisorReviewComment',
    TotalQigsActive: 'TotalQigsActive',
    TotalQigsRequiring: 'TotalQigsRequiring',
    CentreColumn: 'CentreColumn',
    ScriptIdColumn: 'ScriptIdColumn',
    MarksColumn: 'MarksColumn',
    LastMarkerColumn: 'LastMarkerColumn',
    NoteColumn: 'NoteColumn',
    RigOrderColumn: 'RigOrderColumn',
    Centre: 'Centre',
    Scripts: 'Scripts',
	ScriptsAvailable: 'ScriptsAvailable',
	ScriptId: 'ScriptId',
	Status: 'Status',
	FirstScanned: 'FirstScanned',
	Name: 'Name',
	Username: 'UserName',
	ExaminerCode: 'ExaminerCode',
    SpecialistType: 'SpecialistType',
	DeClassifyColumn: 'DeClassifyColumn',
	QuestionItems: 'QuestionItems',
    OrginalSession: 'OrginalSession',
    OrginalClassification: 'OrginalClassification',
    Mark: 'Mark',
    OrginalMarksUpdated: 'OrginalMarksUpdated',
    HideResponse: 'HideResponse',
    Totaltimereused: 'Totaltimereused',
    LastUsed: 'LastUsed',
    TimesReusedInThisSession: 'TimesReusedInThisSession',
    UpdatePending: 'UpdatePending',
    IsReused: 'IsReused',
    IsReusedInThisQIG: 'IsReusedInThisQIG',
    TimesSuspended: 'TimesSuspended',
    IsSharedProvisional: 'IsSharedProvisional'
});

export = gridColumnNames;
